apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  name: {{ include "code-server.fullname" . }}
data:
{{- range $path, $_ := (.Files.Glob "setup/*") }}
  {{- trimPrefix "setup/" $path | nindent 2 }}: |-
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{- end }}