apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  name: {{ include "code-server.fullname" . }}
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc }}
  sudoPassword: {{ .Values.secret.sudoPassword | b64enc }}