apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  name: {{ include "code-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: code-server
      port: {{ .Values.service.port }}
      targetPort: code-server
    {{- range .Values.extraEndpoints }}
    - name: {{ .servicePortName }}
      port: {{ .servicePort }}
      targetPort: {{ .containerPortName }}
    {{- end }}
  selector:
    {{- include "code-server.selectorLabels" . | nindent 4 }}