{{- if .Values.persistentVolume.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  name: {{ include "postgres.fullname" . }}
spec:
  {{- toYaml .Values.persistentVolume.spec | nindent 2 }}
{{- end }}