{{- if .Values.persistentVolume.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  name: {{ include "nexus.fullname" . }}
spec:
  {{- toYaml .Values.persistentVolume.spec | nindent 2 }}
{{- end }}