{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  name: {{ include "nexus.serviceAccountName" . }}
{{- end }}
