apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  name: {{ include "nexus.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: nexus
      port: {{ .Values.service.port }}
      targetPort: nexus
    - name: docker
      port: {{ .Values.service.dockerPort }}
      targetPort: docker
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}